package:
  name: pathfinding
  version: 1.0.18

source:
  path: ./

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas

about:
  home: https://github.com/brean/python-pathfinding
  license: MIT
  summary: "Pathfinding algorithms for python 3."
